FROM python:3.13-slim-trixie@sha256:3dd7cc108ec1493442514f5c2a871af6af0ec31d768ff6e378a93340c3b3db5f
RUN apt-get update && apt-get install -y --no-install-recommends curl libssl3t64 openssl ca-certificates awscli \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir 'moto[server]==5.2.3'
WORKDIR /repo
