FROM python:3.13-slim-bookworm@sha256:5024f48ba9441d4b13a95d3945abc6365538e3a31109833367a1923523c6efed
RUN apt-get update && apt-get install -y --no-install-recommends curl libssl3 openssl ca-certificates awscli \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir 'moto[server]==5.2.3'
WORKDIR /repo
